server:
  port: 8081

spring:
  datasource:
    druid:
      url: jdbc:mysql://8.129.212.55:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true

      username: root
      password: zj123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: package com.xiami.entity
  mapper-locations: classpath:mapper/*.xml
#  开启控制台打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志
logging:
  level:
    #    root日志以INFO级别输出
    #    root: info
    #    此包下所有class以DEBUG级别输出
    com.xiami.dao.*: DEBUG
  #    org.springframework: WARN
  #    org.spring.springboot.dao: debug
  #    mapper: debug

  #  file: log/xiami-blog-dev.log
  #  默认就是下面这个，所以不写也没关系
#  config: classpath:logback-spring.xml

######### 分页插件 ##########
pagehelper:
  #  分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。
  helperDialect: mysql
  #  3.3.0版本可用 - 分页参数合理化，默认false禁用
  #  启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  #  禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: false
  #  //是否支持接口参数来传递分页参数，默认false
  supportMethodsArguments: true
  params: count=countSql
  offsetAsPageNum: true
  #  设置为true时，使用RowBounds分页会进行count查询
  rowBoundsWithCount: true
  #  设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
  #  （相当于没有执行分页查询，但是返回结果仍然是Page类型）
  pageSizeZero: true

auth:
  token-header: Authorization